### ISSUE TITLE
Analisis y diseño

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#27]
**Descripción**
Esta sección contiene los componentes que son el marco teorico  relacionado con el proceso de análisis y diseño del proyecto, así mismo la guía para cualquier inquietud frente a los entre los diferentes procesos

**Tareas**
- [ ] Diagrama de casos de uso
- [ ] Diagramas de clase
- [ ] Diagramas de secuencia
- [ ] Diagramas de actividades
- [ ] Diagramas de componentes
- [ ] Diagramas de infraestructura
- [ ] Documento de analisis y diseño
