### ISSUE TITLE
Bases de datos

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#28]
**Descripción**
Esta sección contiene los procesos relacionados la base de datos y la documentación requerida para el desarrollo coherente y ordenado de almacenamiento del proyecto proyecto

**Tareas**
- [ ] Diagrama entidad - relación
- [ ] Creación de script de base de datos
- [ ] inserción de datos
